version: '3.7'

services:
  payment-agreement-silin-db:
    image: postgres:13
    container_name: xxxx
    restart: unless-stopped
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=xxx
    ports:
      - "5432:5432"