services:
  usuario-db:
    image: mysql:8.0
    container_name: usuario_db_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=valery123
      - MYSQL_DATABASE=usuario_db
      - MYSQL_USER=valery
      - MYSQL_PASSWORD=valery123
    ports:
      - "3308:3306"