version: '3.7'

services:
  usuario-db:
    image: postgres:13
    container_name: usuario_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=valery
      - POSTGRES_PASSWORD=valery123
      - POSTGRES_DB=usuario_db
    ports:
      - "5432:5432"